version: "3"
services:
  core:
    image: env_platform_core
    build: ./core
    ports:
      - "9090:9090"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "9070:27017"
    volumes:
      - ./mongo-database/db:/data/db
