openapi: 3.0.0
info:
  version: 1.0.0
  title: Environment Platform
  description: This is the RESTfull API specification for the environment platform which is developed for the environment ministry
paths:
  /users/{user-id}/requests:
    get:
      description: Returns all the requests related to the user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully returned a list of requests
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: "#/components/schemas/TreeRemovalBasicData"
        "401":
          description: This will return when the authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "404":
          description: This is return because when user cannot be found in user id
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
    post:
      description: Post a new requst
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TreeRemovalForm"
      responses:
        "200":
          description: Successfully save the request
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "401":
          description: This will return when the authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "406":
          description: This is returned when the form validation is failed.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error_type:
                    type: string
        "404":
          description: This is return because when user cannot be found in user id
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
  /users/{user-id}/requests/{request-id}:
    get:
      description: Return the specific request information
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
        - name: request-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully return the request innformation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TreeRemovalObject"
        "401":
          description: This will return when the authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "404":
          description: This is return because either when user or request cannot be found
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
  /users/{user-id}/drafts:
    get:
      description: Returns all the drafts made by the user
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully returned a list of drafts
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TreeRemovalDraftBasicdata"
        "401":
          description: This will return when the authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
        "404":
          description: This is return because user cannot be found
          content:
            application/json:
              schema:
                type: object
                properties:
                  reason:
                    type: string
    post:
      description: Post a new request as a draft
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully post as a draft
  /users/{user-id}/draft/{draft-id}:
    get:
      description: Return the specific draft information
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
        - name: draft-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully return the draft innformation
    patch:
      description: Update exsisting draft information
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
        - name: draft-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully update the draft
    delete:
      description: Delete a specific draft
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
        - name: draft-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully delete the draft
  /users/{user-id}/conversations:
    get:
      description: Get all the message conversations regarding the requests
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrive all the messages
  /users/{user-id}/conversations/{conversation-id}:
    get:
      description: Get the conversation regarding to the specific request
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
        - name: conversation-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      description: Post a new message to the connversation
      parameters:
        - name: user-id
          in: path
          required: true
          schema:
            type: string
        - name: conversation-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /validate:
    post:
      description: This is for the validation part of the map
      responses:
        "200":
          description: OK
  /ministries/{ministry-id}/requests:
    get:
      description: Get all the requests
      parameters:
        - name: ministry-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
  /ministries/{ministry-id}/requests/{request-id}:
    get:
      description: get a specific request
      parameters:
        - name: ministry-id
          description: description
          in: path
          required: true
          schema:
            type: string
        - name: request-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    patch:
      description: Update the exsisting information on the request or assign a ministry
      parameters:
        - name: ministry-id
          in: path
          required: true
          schema:
            type: string
        - name: request-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully update the request
  /ministries/{ministry-id}/conversations:
    get:
      description: Get all the message conversations regarding the requests
      parameters:
        - name: ministry-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successfully retrive all the messages
  /ministries/{ministry-id}/conversations/{conversation-id}:
    get:
      description: Get the conversation regarding to the specific request
      parameters:
        - name: ministry-id
          in: path
          required: true
          schema:
            type: string
        - name: conversation-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
    post:
      description: Post a new message to the connversation
      parameters:
        - name: ministry-id
          in: path
          required: true
          schema:
            type: string
        - name: conversation-id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK

components:
  schemas:
    TreeRemovalBasicData:
      type: array
      items:
        type: object
        properties:
          title:
            type: string
            description: The title of the request
          removalDate:
            type: string
            description: date of the removal
          status:
            type: string
            description: The status of the request
    TreeRemovalForm:
      type: object
      properties:
        title:
          type: string
          description: The title of the request
        removalDate:
          type: string
          description: Removal date of the trees
        reason:
          type: string
        type:
          type: string
        requestedBy:
          type: string
          description: The person who is requesting
        permitRequired:
          type: boolean
        landOwner:
          type: string
          description: Name of the landowner
        treeRemovalAutrhority:
          type: string
        city:
          type: string
        district:
          type: string
        nameOfTheLand:
          type: string
        planNumber:
          type: string
        location:
          type: array
          description: This includes all the points in the polygon
          items:
            type: object
            properties:
              latitude:
                type: number
              longitude:
                type: number
        treeInformation:
          type: array
          description: This includes all the inforemation about the trees which are to be cut
          items:
            type: object
            properties:
              species:
                type: string
              treeNumber:
                type: string
              heightType:
                type: string
                enum: ["Merchantable", "Top"]
              height:
                type: number
                description: This should be in meters
              girth:
                type: number
                description: The girth at the brest height and this should be in centimeters
              logDetails:
                type: array
                items:
                  type: object
                  properties:
                    minGirth:
                      type: number
                      description: minimum girth of the log
                    maxGirth:
                      type: number
                      description: maximum girth of the log
                    height:
                      type: number
                      description: length of the log
    TreeRemovalObject:
      type: object
      properties:
        title:
          type: string
          description: The title of the title
        removalDate:
          type: string
          description: Removal date of the trees
        reason:
          type: string
        type:
          type: string
        requestedBy:
          type: string
          description: The person who is requesting
        permitRequired:
          type: boolean
        landOwner:
          type: string
          description: Name of the landowner
        treeRemovalAutrhority:
          type: string
        city:
          type: string
        district:
          type: string
        nameOfTheLand:
          type: string
        planNumber:
          type: string
        location:
          type: array
          description: This includes all the points in the polygon
          items:
            type: object
            properties:
              latitude:
                type: number
              longitude:
                type: number
        treeInformation:
          type: array
          description: This includes all the inforemation about the trees which are to be cut
          items:
            type: object
            properties:
              species:
                type: string
              treeNumber:
                type: string
              heightType:
                type: string
                enum: ["Merchantable", "Top"]
              height:
                type: number
                description: This should be in meters
              girth:
                type: number
                description: The girth at the brest height and this should be in centimeters
              logDetails:
                type: array
                items:
                  type: object
                  properties:
                    minGirth:
                      type: number
                      description: minimum girth of the log
                    maxGirth:
                      type: number
                      description: maximum girth of the log
                    height:
                      type: number
                      description: length of the log
        progress:
          type: array
          items:
            type: object
            properties:
              authority:
                type: string
                description: This is the respective authority
              status:
                type: string
                description: current status of the request processed by a particular authority
    TreeRemovalDraftBasicdata:
      type: array
      items:
        type: object
        properties:
          title:
            type: string
            description: The title of the request
          removalDate:
            type: string
            description: date of the removal
